### ISSUE TITLE
Overhead light in the main area throws shadows

### ISSUE THREAD

**Issue by elmisback** [elmisback/casa#19]
The overhead light throws unsettling shadows on the kitchen counter space. It also throws my shadow across the kitchen counter while I'm using it, which is distracting. I'd like to try bouncing the overhead light back upward so it diffuses more gently. #18 should also help keep the counter bright.

**Comment by tokyomuskox** [comment]
It's probably just ghosts.

**Comment by elmisback** [comment]
Spectral activity has been confirmed.

**Comment by elmisback** [comment]
The custom shade from #24 should also solve this problem.

**Comment by kevsheb** [comment]
![Ghosts](http://wallpaper-gallery.net/images/ghost/ghost-15.jpg)
